name: 2023-Illukkumbura-JCB-modelling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - ipywidgets
  - jupyter
  - pip
  - pip:
      - pde-rk==0.1.2
      - parameter-space-2d==0.1.4
